services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"

  service1:
    build: ./service1
    ports:
      - "5001:5001"

  service2:
    build: ./service2
    ports:
      - "5002:5002"

  service3:
    build: ./service3
    ports:
      - "5003:5003"
